/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Helloworld的笔记",
  "tagline": "学习笔记 · 思维风暴 · 生活碎片",
  "url": "https://your-blog.pages.dev",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "organizationName": "BullyDoss",
  "projectName": "blog",
  "trailingSlash": false,
  "i18n": {
    "defaultLocale": "zh-CN",
    "locales": [
      "zh-CN"
    ],
    "localeConfigs": {
      "zh-CN": {
        "label": "简体中文"
      }
    },
    "path": "i18n"
  },
  "customFields": {
    "apiBaseUrl": "https://blog-api.bullydoss-blog.workers.dev",
    "r2BucketUrl": "https://pub-xxxxx.r2.dev"
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": false,
        "blog": {
          "routeBasePath": "/",
          "blogTitle": "Helloworld的笔记",
          "blogDescription": "学习笔记 · 思维风暴 · 生活碎片",
          "postsPerPage": 10,
          "blogSidebarCount": "ALL",
          "authorsMapPath": "authors.yml"
        },
        "theme": {
          "customCss": "C:\\Users\\Doss\\Desktop\\Blog\\blog\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "Helloworld的笔记",
      "logo": {
        "alt": "Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "to": "/",
          "label": "首页",
          "position": "left"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "copyright": "Copyright © 2026 Helloworld的笔记. Built with Docusaurus.",
      "links": []
    },
    "prism": {
      "additionalLanguages": [
        "bash",
        "python",
        "javascript",
        "typescript"
      ],
      "theme": {
        "plain": {},
        "styles": []
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "storage": {
    "type": "localStorage",
    "namespace": false
  },
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false,
      "siteStorageNamespacing": false,
      "fasterByDefault": false,
      "mdx1CompatDisabledByDefault": false
    },
    "faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false,
      "gitEagerVcs": false
    },
    "experimental_vcs": {},
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
